blueprint:
  name: Six Button ZigBee Remote
  description: Blueprint for a 6-button remote with configurable actions for short press, long press, and double press.
  domain: automation
  input:
    remote_device_id:
      name: Remote Device ID
      description: Select the remote control device.
      selector:
        device:
          integration: zha
    button_1_short:
      name: Button 1 Short Press Action
      description: Action to run when Button 1 is short-pressed.
      selector:
        action: {}
      default: []
    button_1_long:
      name: Button 1 Long Press Action
      description: Action to run when Button 1 is long-pressed.
      selector:
        action: {}
      default: []
    button_1_double:
      name: Button 1 Double Press Action
      description: Action to run when Button 1 is double-pressed.
      selector:
        action: {}
      default: []
    button_2_short:
      name: Button 2 Short Press Action
      description: Action to run when Button 2 is short-pressed.
      selector:
        action: {}
      default: []
    button_2_long:
      name: Button 2 Long Press Action
      description: Action to run when Button 2 is long-pressed.
      selector:
        action: {}
      default: []
    button_2_double:
      name: Button 2 Double Press Action
      description: Action to run when Button 2 is double-pressed.
      selector:
        action: {}
      default: []
    button_3_short:
      name: Button 3 Short Press Action
      description: Action to run when Button 3 is short-pressed.
      selector:
        action: {}
      default: []
    button_3_long:
      name: Button 3 Long Press Action
      description: Action to run when Button 3 is long-pressed.
      selector:
        action: {}
      default: []
    button_3_double:
      name: Button 3 Double Press Action
      description: Action to run when Button 3 is double-pressed.
      selector:
        action: {}
      default: []
    button_4_short:
      name: Button 4 Short Press Action
      description: Action to run when Button 4 is short-pressed.
      selector:
        action: {}
      default: []
    button_4_long:
      name: Button 4 Long Press Action
      description: Action to run when Button 4 is long-pressed.
      selector:
        action: {}
      default: []
    button_4_double:
      name: Button 4 Double Press Action
      description: Action to run when Button 4 is double-pressed.
      selector:
        action: {}
      default: []
    button_5_short:
      name: Button 5 Short Press Action
      description: Action to run when Button 5 is short-pressed.
      selector:
        action: {}
      default: []
    button_5_long:
      name: Button 5 Long Press Action
      description: Action to run when Button 5 is long-pressed.
      selector:
        action: {}
      default: []
    button_5_double:
      name: Button 5 Double Press Action
      description: Action to run when Button 5 is double-pressed.
      selector:
        action: {}
      default: []
    button_6_short:
      name: Button 6 Short Press Action
      description: Action to run when Button 6 is short-pressed.
      selector:
        action: {}
      default: []
    button_6_long:
      name: Button 6 Long Press Action
      description: Action to run when Button 6 is long-pressed.
      selector:
        action: {}
      default: []
    button_6_double:
      name: Button 6 Double Press Action
      description: Action to run when Button 6 is double-pressed.
      selector:
        action: {}
      default: []

trigger:
  # Button 1 Short Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 1
      args:
        - 0
    id: button_1_short
  # Button 1 Long Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 1
      args:
        - 2
    id: button_1_long
  # Button 1 Double Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 1
      args:
        - 1
    id: button_1_double
  # Button 2 Short Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 2
      args:
        - 0
    id: button_2_short
  # Button 2 Long Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 2
      args:
        - 2
    id: button_2_long
  # Button 2 Double Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 2
      args:
        - 1
    id: button_2_double
  # Button 3 Short Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 3
      args:
        - 0
    id: button_3_short
  # Button 3 Long Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 3
      args:
        - 2
    id: button_3_long
  # Button 3 Double Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 3
      args:
        - 1
    id: button_3_double
  # Button 4 Short Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 4
      args:
        - 0
    id: button_4_short
  # Button 4 Long Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 4
      args:
        - 2
    id: button_4_long
  # Button 4 Double Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 4
      args:
        - 1
    id: button_4_double
  # Button 5 Short Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 5
      args:
        - 0
    id: button_5_short
  # Button 5 Long Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 5
      args:
        - 2
    id: button_5_long
  # Button 5 Double Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 5
      args:
        - 1
    id: button_5_double
  # Button 6 Short Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 6
      args:
        - 0
    id: button_6_short
  # Button 6 Long Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 6
      args:
        - 2
    id: button_6_long
  # Button 6 Double Press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device_id
      command: press_type
      endpoint_id: 6
      args:
        - 1
    id: button_6_double

action:
  - choose:
      - conditions:
          - condition: trigger
            id: button_1_short
        sequence: !input button_1_short
      - conditions:
          - condition: trigger
            id: button_1_long
        sequence: !input button_1_long
      - conditions:
          - condition: trigger
            id: button_1_double
        sequence: !input button_1_double
      - conditions:
          - condition: trigger
            id: button_2_short
        sequence: !input button_2_short
      - conditions:
          - condition: trigger
            id: button_2_long
        sequence: !input button_2_long
      - conditions:
          - condition: trigger
            id: button_2_double
        sequence: !input button_2_double
      - conditions:
          - condition: trigger
            id: button_3_short
        sequence: !input button_3_short
      - conditions:
          - condition: trigger
            id: button_3_long
        sequence: !input button_3_long
      - conditions:
          - condition: trigger
            id: button_3_double
        sequence: !input button_3_double
      - conditions:
          - condition: trigger
            id: button_4_short
        sequence: !input button_4_short
      - conditions:
          - condition: trigger
            id: button_4_long
        sequence: !input button_4_long
      - conditions:
          - condition: trigger
            id: button_4_double
        sequence: !input button_4_double
      - conditions:
          - condition: trigger
            id: button_5_short
        sequence: !input button_5_short
      - conditions:
          - condition: trigger
            id: button_5_long
        sequence: !input button_5_long
      - conditions:
          - condition: trigger
            id: button_5_double
        sequence: !input button_5_double
      - conditions:
          - condition: trigger
            id: button_6_short
        sequence: !input button_6_short
      - conditions:
          - condition: trigger
            id: button_6_long
        sequence: !input button_6_long
      - conditions:
          - condition: trigger
            id: button_6_double
        sequence: !input button_6_double
