blueprint:
  name: Configurable Remote Control
  description: Blueprint for a 6-button remote with configurable actions for short press, long press, and double press.
  domain: automation
  input:
    button_1_short:
      name: Button 1 Short Press Action
      description: Action to run when Button 1 is short-pressed.
      selector:
        action: {}
    button_1_long:
      name: Button 1 Long Press Action
      description: Action to run when Button 1 is long-pressed.
      selector:
        action: {}
    button_1_double:
      name: Button 1 Double Press Action
      description: Action to run when Button 1 is double-pressed.
      selector:
        action: {}
    button_2_short:
      name: Button 2 Short Press Action
      description: Action to run when Button 2 is short-pressed.
      selector:
        action: {}
    button_2_long:
      name: Button 2 Long Press Action
      description: Action to run when Button 2 is long-pressed.
      selector:
        action: {}
    button_2_double:
      name: Button 2 Double Press Action
      description: Action to run when Button 2 is double-pressed.
      selector:
        action: {}
    button_3_short:
      name: Button 3 Short Press Action
      description: Action to run when Button 3 is short-pressed.
      selector:
        action: {}
    button_3_long:
      name: Button 3 Long Press Action
      description: Action to run when Button 3 is long-pressed.
      selector:
        action: {}
    button_3_double:
      name: Button 3 Double Press Action
      description: Action to run when Button 3 is double-pressed.
      selector:
        action: {}
    button_4_short:
      name: Button 4 Short Press Action
      description: Action to run when Button 4 is short-pressed.
      selector:
        action: {}
    button_4_long:
      name: Button 4 Long Press Action
      description: Action to run when Button 4 is long-pressed.
      selector:
        action: {}
    button_4_double:
      name: Button 4 Double Press Action
      description: Action to run when Button 4 is double-pressed.
      selector:
        action: {}
    button_5_short:
      name: Button 5 Short Press Action
      description: Action to run when Button 5 is short-pressed.
      selector:
        action: {}
    button_5_long:
      name: Button 5 Long Press Action
      description: Action to run when Button 5 is long-pressed.
      selector:
        action: {}
    button_5_double:
      name: Button 5 Double Press Action
      description: Action to run when Button 5 is double-pressed.
      selector:
        action: {}
    button_6_short:
      name: Button 6 Short Press Action
      description: Action to run when Button 6 is short-pressed.
      selector:
        action: {}
    button_6_long:
      name: Button 6 Long Press Action
      description: Action to run when Button 6 is long-pressed.
      selector:
        action: {}
    button_6_double:
      name: Button 6 Double Press Action
      description: Action to run when Button 6 is double-pressed.
      selector:
        action: {}

trigger:
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    id: button_1_short
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_long_press
    subtype: button_1
    id: button_1_long
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    id: button_1_double
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    id: button_2_short
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_long_press
    subtype: button_2
    id: button_2_long
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    id: button_2_double
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    id: button_3_short
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_long_press
    subtype: button_3
    id: button_3_long
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_double_press
    subtype: button_3
    id: button_3_double
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    id: button_4_short
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_long_press
    subtype: button_4
    id: button_4_long
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_double_press
    subtype: button_4
    id: button_4_double
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_short_press
    subtype: button_5
    id: button_5_short
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_long_press
    subtype: button_5
    id: button_5_long
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_double_press
    subtype: button_5
    id: button_5_double
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_short_press
    subtype: button_6
    id: button_6_short
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_long_press
    subtype: button_6
    id: button_6_long
  - platform: device
    device_id: !input remote_device
    domain: zha
    type: remote_button_double_press
    subtype: button_6
    id: button_6_double

action:
  - choose:
      - conditions:
          - condition: trigger
            id: button_1_short
        sequence: !input button_1_short
      - conditions:
          - condition: trigger
            id: button_1_long
        sequence: !input button_1_long
      - conditions:
          - condition: trigger
            id: button_1_double
        sequence: !input button_1_double
      - conditions:
          - condition: trigger
            id: button_2_short
        sequence: !input button_2_short
      - conditions:
          - condition: trigger
            id: button_2_long
        sequence: !input button_2_long
      - conditions:
          - condition: trigger
            id: button_2_double
        sequence: !input button_2_double
      - conditions:
          - condition: trigger
            id: button_3_short
        sequence: !input button_3_short
      - conditions:
          - condition: trigger
            id: button_3_long
        sequence: !input button_3_long
      - conditions:
          - condition: trigger
            id: button_3_double
        sequence: !input button_3_double
      - conditions:
          - condition: trigger
            id: button_4_short
        sequence: !input button_4_short
      - conditions:
          - condition: trigger
            id: button_4_long
        sequence: !input button_4_long
      - conditions:
          - condition: trigger
            id: button_4_double
        sequence: !input button_4_double
      - conditions:
          - condition: trigger
            id: button_5_short
        sequence: !input button_5_short
      - conditions:
          - condition: trigger
            id: button_5_long
        sequence: !input button_5_long
      - conditions:
          - condition: trigger
            id: button_5_double
        sequence: !input button_5_double
      - conditions:
          - condition: trigger
            id: button_6_short
        sequence: !input button_6_short
      - conditions:
          - condition: trigger
            id: button_6_long
        sequence: !input button_6_long
      - conditions:
          - condition: trigger
            id: button_6_double
        sequence: !input button_6_double
